### ISSUE TITLE
Core/select + collection/ext-select

### ISSUE THREAD

**Issue by navix** [ngx-kit/ngx-kit#255]
## TODO

* [x] Select
* [x] Data-providing
* [x] Filtering
* [x] Custom filtering
* [x] Multi-select
* [x] Custom search (autocomplete)
* [x] Search debounce
* [x] Clearable
* [x] Placeholder
* [x] Disabled state
* [x] Forms validation states
* [ ] ~Creatable~
* [ ] ~Force ngModel update on input (optional)~
* [ ] ~Clean-up input on esc (optional)~
* [ ] ~Multiselect: allow duplicates (optional)~
* [ ] ~Pass options through DI~
* [ ] ~Limits~
* [ ] ~Grouping~
* [ ] ~Scroll to active~

#### Fixes

* [x] Stop current async request on update
* [x] Do not show arrow if it is default autocomplete
* [x] Initial inputView (for AG async load)
* [x] Restore active handlers 
* [x] Activate first if not active after filter
* [x] Open items on ArrowUp/ArrowDown
* [x] Drop async request on items close
* [x] Focus to input after delete item in multi-mode
* [x] Remove last of multiple on Backspace
* [x] Check streams unsubs on destroy
* [ ] ~Use Angular Differs~

##### Polishing

* [x] Refactor&naming
* [x] `*Changes()` getters
* [x] Styling
* [x] Responsive
* [x] Firefox/Edge tests
* [x] Performance tests
* [ ] ~improve a11y: aria-live=assertive + sreen-reader message~
* [x] Docs
* [x] Remove ui-autocomplete

**Comment by navix** [comment]
Released with [7.1.0](https://github.com/ngx-kit/ngx-kit/releases/tag/7.1.0)
